
#ifndef FREEXCOMMONTOOLUI_EXPORT_H
#define FREEXCOMMONTOOLUI_EXPORT_H

#ifdef FREEXCOMMONTOOLUI_STATIC_DEFINE
#  define FREEXCOMMONTOOLUI_EXPORT
#  define FREEXCOMMONTOOLUI_NO_EXPORT
#else
#  ifndef FREEXCOMMONTOOLUI_EXPORT
#    ifdef FreeXCommonToolUi_EXPORTS
        /* We are building this library */
#      define FREEXCOMMONTOOLUI_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define FREEXCOMMONTOOLUI_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef FREEXCOMMONTOOLUI_NO_EXPORT
#    define FREEXCOMMONTOOLUI_NO_EXPORT 
#  endif
#endif

#ifndef FREEXCOMMONTOOLUI_DEPRECATED
#  define FREEXCOMMONTOOLUI_DEPRECATED __declspec(deprecated)
#endif

#ifndef FREEXCOMMONTOOLUI_DEPRECATED_EXPORT
#  define FREEXCOMMONTOOLUI_DEPRECATED_EXPORT FREEXCOMMONTOOLUI_EXPORT FREEXCOMMONTOOLUI_DEPRECATED
#endif

#ifndef FREEXCOMMONTOOLUI_DEPRECATED_NO_EXPORT
#  define FREEXCOMMONTOOLUI_DEPRECATED_NO_EXPORT FREEXCOMMONTOOLUI_NO_EXPORT FREEXCOMMONTOOLUI_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef FREEXCOMMONTOOLUI_NO_DEPRECATED
#    define FREEXCOMMONTOOLUI_NO_DEPRECATED
#  endif
#endif

#endif /* FREEXCOMMONTOOLUI_EXPORT_H */
