SET(HGBDP_DIR "" CACHE PATH "Set to HGBDP install path")

set(FIND_HGBDP_ROOT_PATH
	${HGBDP_DIR}
    $ENV{HGBDP_BUILD_DIR}
    $ENV{HGBDP_DIR}
    $ENV{HGBDPDIR}
    $ENV{HGBDP_ROOT}
    ~/Library/Frameworks
    /Library/Frameworks
    /usr/local
    /usr
    /sw
    /opt/local
    /opt/csw
    /opt
)

FIND_PATH(HGBDP_INCLUDE_DIR bdpDB/GxPluginBase.h
	PATHS 
		${FIND_HGBDP_ROOT_PATH}
	PATH_SUFFIXES
		/include/
	)

MACRO(FIND_HGBDP_LIBRARY MYLIBRARY MYLIBRARYNAME)

FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${FIND_HGBDP_ROOT_PATH}
    PATH_SUFFIXES
        /lib/
        /lib64/
        /build/lib/
        /build/lib64/
        /Build/lib/
        /Build/lib64/
     )
	 
ENDMACRO(FIND_HGBDP_LIBRARY MYLIBRARY LIBRARYNAME)

FIND_HGBDP_LIBRARY( HGBDP_COMMON_LIBRARY bdpCommon )
FIND_HGBDP_LIBRARY( HGBDP_COMMON_LIBRARY_DEBUG bdpCommond)

FIND_HGBDP_LIBRARY( HGBDP_ALGOR_LIBRARY bdpAlgor )
FIND_HGBDP_LIBRARY( HGBDP_ALGOR_LIBRARY_DEBUG bdpAlgord)

FIND_HGBDP_LIBRARY( HGBDP_DB_LIBRARY bdpDB )
FIND_HGBDP_LIBRARY( HGBDP_DB_LIBRARY_DEBUG bdpDBd)

FIND_HGBDP_LIBRARY( HGBDP_UTIL_LIBRARY bdpUtil )
FIND_HGBDP_LIBRARY( HGBDP_UTIL_LIBRARY_DEBUG bdpUtild)

FIND_HGBDP_LIBRARY( HGBDP_SCENE_LIBRARY bdpScene )
FIND_HGBDP_LIBRARY( HGBDP_SCENE_LIBRARY_DEBUG bdpScened)

FIND_HGBDP_LIBRARY( HGBDP_OBJECT_LIBRARY bdpObject )
FIND_HGBDP_LIBRARY( HGBDP_OBJECT_LIBRARY_DEBUG bdpObjectd)

FIND_HGBDP_LIBRARY( HGBDP_TOOL_LIBRARY bdpTool )
FIND_HGBDP_LIBRARY( HGBDP_TOOL_LIBRARY_DEBUG bdpToold)

FIND_HGBDP_LIBRARY( HGBDP_NETWORK_LIBRARY bdpNet )
FIND_HGBDP_LIBRARY( HGBDP_NETWORK_LIBRARY_DEBUG bdpNetd)

IF((HGBDP_COMMON_LIBRARY OR HGBDP_COMMON_LIBRARY_DEBUG) AND HGBDP_INCLUDE_DIR)
    SET(HGBDP_FOUND "YES")
	include_directories("${HGBDP_INCLUDE_DIR}")
	SET(HGBDP_LIBRARIES
		debug ${HGBDP_COMMON_LIBRARY_DEBUG} optimized ${HGBDP_COMMON_LIBRARY}
		debug ${HGBDP_ALGOR_LIBRARY_DEBUG} optimized ${HGBDP_ALGOR_LIBRARY}
		debug ${HGBDP_DB_LIBRARY_DEBUG} optimized ${HGBDP_DB_LIBRARY}
		debug ${HGBDP_UTIL_LIBRARY_DEBUG} optimized ${HGBDP_UTIL_LIBRARY}
		debug ${HGBDP_SCENE_LIBRARY_DEBUG} optimized ${HGBDP_SCENE_LIBRARY}
		debug ${HGBDP_OBJECT_LIBRARY_DEBUG} optimized ${HGBDP_OBJECT_LIBRARY}
		debug ${HGBDP_TOOL_LIBRARY_DEBUG} optimized ${HGBDP_TOOL_LIBRARY}
		debug ${HGBDP_NETWORK_LIBRARY_DEBUG} optimized ${HGBDP_NETWORK_LIBRARY}
		)
ENDIF((HGBDP_COMMON_LIBRARY OR HGBDP_COMMON_LIBRARY_DEBUG) AND HGBDP_INCLUDE_DIR)


